# Generated by Django 5.2.8 on 2025-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('lugar', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
    ]
