# Generated by Django 5.2.8 on 2025-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
